---
kind: pipeline
name: website

clone:
  depth: 1

steps:
  - name: build - frontend
    image: node:9.8.0-alpine
    volumes:
      - name: npm
        path: /drone/src/node_modules
    commands:
      - npm config set loglevel info
      - npm install
  - name: build - jekyll deps
    image: ruby:2.5.0-alpine
    volumes:
      - name: npm
        path: /drone/src/node_modules
    environment:
      ENV: 'production'
      RAKE_ENV: 'production'
    commands:
      - apk add -U build-base
      - bundle install
      - bundle exec rake build:deploy
  - name: deploy
    image: appleboy/drone-git-push
    remote: dokku@jacky.wtf:jacky-wtf-static
    branch: master
    local_ref: HEAD
