---
kind: pipeline
name: website

pipeline:
  git_push:
    image: appleboy/drone-git-push
    remote: dokku@jacky.wtf:jacky-wtf-static
    branch: master
    local_ref: HEAD

clone:
  depth: 1

steps:
  - name: frontend building
    image: node:9.8.0-alpine
    commands:
      - npm install
  - name: site building and testing
    image: ruby:2.5.0-alpine
    commands:
      - apk add -U build-base
      - bundle install
      - bundle exec rake build:dev spec
