---
kind: pipeline
name: website

clone:
  depth: 1

steps:
  - name: build - frontend
    image: node:9.8.0-alpine
    volumes:
      - name: npm
        path: /drone/src/node_modules
    commands:
      - npm config set loglevel debug
      - npm install
  - name: build - jekyll deps
    image: ruby:2.5.0-alpine
    volumes:
      - name: npm
        path: /drone/src/node_modules
      - name: ruby
        path: /drone/src/vendor/bundle
    environment:
      ENV: 'test'
    commands:
      - apk add -U build-base
      - bundle install --deployment --binstubs=vendor/bin
      - vendor/bin/rake build:deploy
      - vendor/bin/rake rake spec
  - name: deploy
    image: appleboy/drone-git-push
    remote: dokku@jacky.wtf:jacky-wtf-static
    branch: master
    local_ref: HEAD
