---
kind: pipeline
name: website

clone:
  depth: 1

steps:
  - name: frontend building
    image: node:9.8.0-alpine
    volumes:
      - name: cache
        path: ./node_modules
    commands:
      - npm install
  - name: jekyll dep fetching
    image: ruby:2.5.0-alpine
    commands:
      - apk add -U build-base
      - bundle install
  - name: jekyll site building
    image: ruby:2.5.0-alpine
    commands:
      - bundle exec rake build:dev spec

volumes:
  - name: cache
    temp: {}
