---
kind: pipeline
name: default
steps:
  - name: frontend building
    image: node:9.8.0-alpine
    commands:
      - npm install
  - name: website building
    image: ruby:2.5.0-alpine
    commands:
      - apk add -U build-base
      - bundle install
