---
kind: pipeline
name: default
steps:
  - name: frontend building
    image: node:alpine
    commands:
      - npm install
  - name: website building
    image: ruby
    commands:
      - bundle install
