---
kind: pipeline
name: website

clone:
  depth: 1

steps:
  - name: frontend building
    image: node:9.8.0-alpine
    commands:
      - npm install
  - name: site building and testing
    image: ruby:2.5.0-alpine
    commands:
      - apk add -U build-base
      - bundle install
      - bundle exec rake build:dev spec
