# vim: set nospell:
source: 'src'
destination: '_site'
layouts_dir: 'src/_layouts'
plugins_dir: 'plugins'
filter_entries: []

# Metadata about the site that we'd use very very often.
# {{{ Metadata
name: 'Jacky Alciné'
author: 'Jacky Alciné'
url: 'https://jacky.wtf'
description: |
  A young Black male from Brooklyn, New York in Oakland, California learning
  more about the world and now working to help make it way more secure for the
  people who live in it. So much to learn and yet so little time!
# }}}

# Time & encoding.
timezone: 'America/Los_Angeles'
encoding: 'utf-8'

permalink: "/weblog/:title/"
show_drafts: false
lsi: true
future: false
relative_permalinks: false
markdown: kramdown

exclude:
  - _site
  - .asset_cache

# {{{ Markdown renderer options
kramdown:
  extensions:
    - footnotes
    - autolink
    - space_after_headers
    - highlight
    - fenced_code_blocks
    - disabled_indented_code_blocks
    - underline
    - with_toc_data
    - prettify
# }}}

defaults:
  -
    scope:
      path: ""
    values:
      components:
        header: true
        footer: true

assets:
  debug: true
  autowrite: true
  compress:
    css: true
    js: true
  prefix: "/assets"
  asset:
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "bundle.css"
  sources:
    - _assets/css
    - _assets/images
    - _assets/img
    - _assets/js
  features:
    liquid: true

navigation:
  links:
    - name: Weblog
      uri: /weblog/
    - name: Gear
      uri: /gear/
    - name: Work
      uri: /work/
    - name: Crypto
      uri: /crypto/
    - name: Press
      uri: /press/

gpg:
  fingerprint: "0x4DEFFC9FF82E8908"
