# vim: nospell :
source: 'src'
destination: '_site'
plugins: 'plugins'
layouts: 'src/_layouts'

name: 'Jacky Alciné'
author: 'Jacky Alciné'
url: 'http://jalcine.me'
timezone: 'America/New_York'
description: |
  The site of a young guy learning about computers and
  the things that work with them. Growing a bit of a
  Starkian and Waynian complex, this'll be a hub of
  information of said growth.

pagination_path: 'weblog/:num'
permalink: '/weblog/:title'
relative_permalinks: false
lsi: false
show_drafts: false
future: false

exclude:
  - '_layouts'
  - '_includes'
  - '_css'

links:
  navigation:
    -
      title: "Weblog"
      icon: "pencil"
      link: "/weblog"
    -
      title: "About"
      icon: "about"
      link: "/about"
  social:
    -
      title: "Twitter"
      icon: "twitter"
      link: "https://twitter.com/jackyalcine"
    -
      title: "Github"
      icon: "github"
      link: "https://github.com/jalcine"
    -
      title: "Reddit"
      icon: "reddit"
      link: "https://reddit.com/user/jackyalcine"
    -
      title: "LinkedIn"
      icon: "linkedin"
      link: "https://linkedin.com/in/jackyalcine"
    -
      title: "Keybase"
      icon: "key"
      link: "https://keybase.io/jackyalcine"
    -
      title: "Keybase"
      icon: "key"
      link: "https://keybase.io/jackyalcine"
