# vim: nospell :
source: 'src'
destination: '_site'
plugins: 'plugins'
layouts: 'src/_layouts'

name: 'Jacky Alciné'
author: 'Jacky Alciné'
url: 'http://jalcine.me'
timezone: 'America/New_York'
description: |
  The site of a young guy learning about computers and
  the things that work with them. Growing a bit of a
  Starkian and Waynian complex, this'll be a hub of
  information of said growth.

pagination_path: 'weblog/:num'
permalink: '/weblog/:title'
relative_permalinks: false
lsi: false
show_drafts: false
future: false

exclude:
  - '_layouts'
  - '_includes'
  - '_css'

nav_links:
  -
    title: "Weblog"
    icon: "pencil"
    link: "/weblog"
  -
    title: "About"
    icon: "penci"
    link: "/about"
  -
    title: "Elsewhere"
    icon: "pencil"
    link: "/social"
