---
build_drafts: true
show_drafts: true
incremental: true
verbose: false
port: 1993

assets:
  compression: false
  debug: false
  verbose: false
  gzip: false
  defaults:
    js:
      integrity: false
      prefetch: false
    css:
      integrity: false
      prefetch: false
    img:
      integrity: false
      prefetch: false

webmentions:
  debug: false
  pages: true
  collections: true
  pause_lookups: false
  username: jacky.wtf
  cache_folder: .cache/webmention
  cache_bad_uris_for: 1
  legacy_domains:
    - "http://jacky.wtf"
    - "http://jalcine.me"
    - "http://www.jalcine.me"
    - "https://jalcine.me"
    - "https://www.jacky.wtf"
    - "https://www.jalcine.me"
  js:
    uglify: false
    deploy: false
    destination: _assets/js
  templates:
    likes: src/_includes/webmentions/likes.html
    links: src/_includes/webmentions/links.html
    posts: src/_includes/webmentions/posts.html
    replies: src/_includes/webmentions/replies.html
    reposts: src/_includes/webmentions/reposts.html

pagination:
  debug: false

isso_host: comments.jacky.vagrant.test

analytics:
  host: analytics.jacky.vagrant.test
  site_id: 1
