# vim: nospell
name: "jalciné"
author: "Jacky Alciné"
url: "http://jalcine.me"
description: "A little collection of text and images."
timezone: "America/New_York"
source: src

# Blog specifics.
future: false
show_drafts: false
relative_permalinks: false
lsi: false
permalink: "/weblog/:title"
paginate: 10
paginate_path: "/weblog/:num"

gems:
  - jekyll-compass
  - jekyll-haml
  - jekyll-mentions
  - jemoji

# Markdown engine.
pygments: true
redcarpet:
  extensions: 
    - footnotes
    - autolink
    - subscript
    - fenced_code_blocks

# Don't bother with theses.
exclude:
  - 'bin'
  - "*.md"
  - "*file"
  - "*config*"
  - 'sass'
  - '*tags*'

# Do it when I was born.
port: 1993
