---
---

destination: _site/
source: src/
layouts_dir: src/_layouts/
plugins_dir: plugins/
filter_entries: []
strict_front_matter: false
include:
  - _pages
  - _faq
  - _events
  - _projects
  - _portfolio

# Metadata about the site that we'd use very very often.
# {{{ Metadata
name: "@jackyalciné"
author: Jacky Alciné
url: https://jacky.wtf
byline: Jacky Alciné is a developer and educator.
blurb: |
  Jacky is a software developer that focuses on the ease of access of user
  security on the Web as well as digital literacy for silicon based consumer
  networked electronics (or "tech"). My mission is to carry out the objective
  of my ancestors and elders: to focus on the liberation of my people and the
  restoration of the legacy of the descendants of the Afrikan Diaspora.
description: |
  Jacky is a New Yorker in Oakland that continues to aim to make change in the
  world via technology and education.

timezone: America/Los_Angeles
encoding: utf-8
incremental: true

permalink: /weblog/:title/
show_drafts: false
lsi: true
future: false
relative_permalinks: false
markdown: kramdown

tag_page_layout: tags
tag_feed_layout: tag_feed
tag_page_dir: weblog/tag/
tag_feed_dir: feeds/tags/

exclude:
  - _site
  - .asset_cache

kramdown:
  syntax_highlighter: rouge
  toc_levels: 1..5
  auto_ids: true
  transparent: true
  extensions:
    - footnotes
    - autolink
    - space_after_headers
    - highlight
    - fenced_code_blocks
    - disabled_indented_code_blocks
    - underline
    - with_toc_data
    - prettify

defaults:
  -
    scope:
      path: ""
    values:
      layout: base
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      image: none
  -
    scope:
      path: "_portfolio"
      type: portfolios
    values:
      layout: portfolio
  -
    scope:
      path: "_projects"
    values:
      layout: project

collections:
  faq:
    output: true
    layout: faq
  events:
    output: true
    layout: event
  projects:
    output: true
    layout: project
  portfolio:
    output: true
    layout: portfolio

# collections:
#   portfolio:
#     output: true
#     permalink: /:collection/:path/
#     title: Portfolio

assets:
  autoprefixer:
    browsers:
      - last 2 versions
  debug: false
  autowrite: true
  digest: true
  strict: true
  integrity: true
  plugins:
    compression:
      css:
        enabled: true
      js:
        enabled: true
  prefix: /assets
  asset:
    - '*.png'
    - '*.jpg'
    - '*.jpeg'
    - '*.gif'
  sources:
    - _assets/css
    - _assets/images
    - _assets/favicon
    - _assets/js
    - node_modules

jekyll-mentions: https://twitter.com

gpg:
  fingerprint: 0x4DEFFC9FF82E8908

jekyll_analytics:
  Piwik:
    url: lighthouse.jacky.wtf
    siteId: "1234"

webmentions:
  pause_lookups: false
  username: jackyalcine
  cache_folder: .cache/webmention
  cache_bad_uris_for: 10
  legacy_domains:
    - "http://jalcine.me"
    - "http://www.jalcine.me"
    - "https://jalcine.me"
    - "https://www.jalcine.me"
  throttle_lookups:
    last_week: daily
    last_month: weekly
    last_year: every 2 weeks
    older: monthly

autolink_email:
  link_attr: class="email-link" # attributes to add to the link
  skip_tags: ["pre", "code"]    # tags to skip
  escape: true

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    day: /:year/:month/:day/
    tag: /tag/:name/
    category: /category/:name/

liquid:
  error_mode: strict
