---
destination: _site/
source: src/
layouts_dir: src/_layouts/
plugins_dir: plugins/
strict_front_matter: false

# Metadata about the site that we'd use very very often.
# {{{ Metadata
name: jackyalciné
name_safe: jackyalcine
author: Jacky Alciné
url: https://jacky.wtf
byline: Jacky Alciné is a developer and educator.
blurb: |
  Jacky is a software developer that focuses on the ease of access of user
  security on the Web as well as digital literacy for silicon based consumer
  networked electronics (or "tech"). My mission is to carry out the objective
  of my ancestors and elders: to focus on the liberation of my people and the
  restoration of the legacy of the descendants of the Afrikan Diaspora.
description: |
  Jacky is a New Yorker in Oakland that continues to aim to make change in the
  world via technology and education.
timezone: America/Los_Angeles
encoding: utf-8
incremental: true
source: ./src/

permalink: /weblog/:title/
build_drafts: false
show_drafts: false
lsi: true
future: false
relative_permalinks: false
markdown: kramdown

pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: 12
  permalink: '/page/:num/'
  limit: 5
  sort_reverse: true
  sort_field: 'date'

tag_feed_dir: feeds/tags/
tag_feed_layout: tag_feed
tag_page_dir: weblog/tag/
tag_page_layout: tags

exclude:
  - _assets
  - .*

kramdown:
  syntax_highlighter: rouge
  auto_ids: true

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      components:
        header: true
        footer: true
  -
    scope:
      path: "_faq"
      type: "faq"
    values:
      layout: "faq"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      image: none
  -
    scope:
      path: "_drafts"
      type: "drafts"
    values:
      layout: post
      image: none

collections:
  events:
    output: true
    layout: event
  faq:
    output: true
    layout: faq
  pages:
    output: true
    layout: page
  portfolio:
    output: true
    layout: portfolio
  posts:
    output: true
    layout: post
  drafts:
    output: true
    layout: post
  projects:
    output: true
    layout: project

assets:
  destination: '/assets'
  compression: true
  gzip: true
  cdn:
    baseurl: true
  defaults:
    js:
      integrity: true
      prefetch: true
    css:
      integrity: true
      prefetch: true
    img:
      integrity: true
      prefetch: true
  caching:
    path: '.cache/assets'
    type: file
    enabled: true
  sources:
    - _assets/files
    - _assets/favicon
    - ../node_modules
  plugins:
    css:
      autoprefixer:
        browsers:
          - "last 2 versions"
          - "IE > 9"

jekyll-mentions: https://twitter.com

gpg:
  fingerprint: "0x4DEFFC9FF82E8908"

analytics:
  host: analytics.jacky.wtf
  site_id: 1

webmentions:
  debug: false
  pages: true
  collections: true
  pause_lookups: false
  username: jacky.wtf
  cache_folder: .cache/webmention
  cache_bad_uris_for: 1
  legacy_domains:
    - "http://jacky.wtf"
    - "http://jalcine.me"
    - "http://www.jalcine.me"
    - "https://jalcine.me"
    - "https://www.jacky.wtf"
    - "https://www.jalcine.me"
  js:
    uglify: true
    deploy: false
    destination: _assets/js
  templates:
    webmentions: src/_includes/webmentions/webmentions.html

autolink_email:
  link_attr: class="email-link" # attributes to add to the link
  skip_tags: ["pre", "code"]    # tags to skip
  escape: true

archives:
  enabled: all
  layout: archive
  permalinks:
    year: /weblog/archives/:year/
    month: /weblog/archives/:year/:month/
    day: /weblog/archvies/:year/:month/:day/
    tag: /weblog/archives/tag/:name/
    category: /weblog/archives/category/:name/

liquid:
  error_mode: strict

isso_host: comments.jacky.wtf
category_path: weblog/categories/

jekyll_tidy:
  compress_html: true
