# vim: set nospell:
source: 'src'
destination: '_site'
layouts_dir: 'src/_layouts'
plugins_dir: 'plugins'
filter_entries: []

# Metadata about the site that we'd use very very often.
# {{{ Metadata
name: 'Jacky Alciné'
author: 'Jacky Alciné'
url: 'https://jacky.wtf'
byline: Jacky Alciné is a developer and educator.
blurb: |
  Jacky is a software developer that focuses on the ease of access of user
  security on the Web as well as digital literacy for silicon based consumer
  networked electronics (or "tech"). My mission is to carry out the objective
  of my ancestors and elders: to focus on the liberation of my people and the
  restoration of the legacy of the descendants of the Afrikan Diaspora.
 
description: |
  Jacky is a New Yorker in Oakland that continues to aim to make change in the
  world via technology and education.
# }}}

# Time & encoding.
timezone: 'America/Los_Angeles'
encoding: 'utf-8'

permalink: "/weblog/:title/"
show_drafts: false
lsi: true
future: false
relative_permalinks: false
markdown: kramdown

exclude:
  - _site
  - .asset_cache

# {{{ Markdown renderer options
kramdown:
  extensions:
    - footnotes
    - autolink
    - space_after_headers
    - highlight
    - fenced_code_blocks
    - disabled_indented_code_blocks
    - underline
    - with_toc_data
    - prettify
# }}}

defaults:
  -
    scope:
      path: ""
    values:
      components:
        header: true
        footer: true

assets:
  debug: true
  autowrite: true
  compress:
    css: true
    js: true
  prefix: "/assets"
  asset:
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "bundle.css"
  sources:
    - _assets/css
    - _assets/images
    - _assets/img
    - _assets/js
  features:
    liquid: true

gpg:
  fingerprint: "0x4DEFFC9FF82E8908"
