---
build_drafts: true
show_drafts: true
incremental: true
verbose: true
port: 1993

assets:
  compression: false
  debug: true
  verbose: true
  gzip: false
  defaults:
    js:
      integrity: true
      prefetch: true
    css:
      integrity: true
      prefetch: true
    img:
      integrity: true
      prefetch: true


webmentions:
  debug: true
  pause_lookups: true

pagination:
  debug: true

isso_host: comments.jacky.vagrant.test

analytics:
  host: analytics.jacky.vagrant.test
  site_id: 1
