---
build_drafts: true
show_drafts: true
incremental: false
url: 'http://localhost:1993'

assets:
  compression: false
  debug: false
  verbose: false
  gzip: false

webmentions:
  debug: true
  pause_lookups: true
  throttle_lookups:
    last_week: weekly
    last_month: monthly
    last_year: yearly
    older: yearly

isso_host: comments.jacky.vagrant.test

analytics:
  host: analytics.jacky.vagrant.test
  site_id: 1
