# vim: nospell :
source: 'src'
destination: '_site'
plugins: 'plugins'
layouts: 'src/_layouts'

name: 'Jacky Alciné'
author: 'Jacky Alciné'
url: 'http://jalcine.me'
timezone: 'America/New_York'
description: |
  The site of a young Black male living in New York City learning about the
  world and the people within it. The education he was brought up
  with was broken by default, and is currently attempting to learn what
  he should have known a decade ago. He's also a bit of a Afrofuturist.

pagination_path: 'weblog/:num'
permalink: '/weblog/:title'
relative_permalinks: false
lsi: false
show_drafts: false
future: false

exclude:
  - '_layouts'
  - '_includes'
  - '_css'

links:
  navigation:
    -
      title: "Weblog"
      icon: "pen"
      link: "/weblog"
    -
      title: "About"
      icon: "home"
      link: "/about"
  social:
    -
      title: "Twitter"
      icon: "twitter"
      link: "https://twitter.com/jackyalcine"
    -
      title: "Github"
      icon: "github"
      link: "https://github.com/jalcine"
    -
      title: "Reddit"
      icon: "reddit"
      link: "https://reddit.com/user/jackyalcine"
    -
      title: "LinkedIn"
      icon: "linkedin"
      link: "https://linkedin.com/in/jackyalcine"
    -
      title: "Keybase"
      icon: "lock"
      link: "https://keybase.io/jackyalcine"
    -
      title: "GPG"
      icon: "key"
      link: "/gpg"
    -
      title: "Stack Overflow"
      icon: "stackoverflow"
      link: "https://stackoverflow.com/users/602588/jackyalcine"
    -
      title: "Last.FM"
      icon: "lastfm"
      link: "https://last.fm/user/jackyalcine"
    -
      title: "Goodreads"
      icon: "pen"
      link: "https://www.goodreads.com/jalcine"
