name: Jacky Alciné
url: http://jalcine.me
description: A little ol' collection of text and images.
timezone: America/New_York

# Blog specifics.
future: false
show_drafts: false
relative_permalinks: true
lsi: true
permalinks: "/weblog/:year/:title"
paginate_path: "/weblog/page/:num"

# Markdown engine.
pygments: true
redcarpet:
  extensions:
    - footnotes
    - autolink
    - smart
    - tables
    - strikethrough
    - superscript

# Don't bother with theses.
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - README
  - Rakefile
  - config.ru
  - README.md

sass:
  syntax: scss
  style: compressed
