---
build_drafts: true
show_drafts: true
incremental: false
url: 'http://localhost:1993'

assets:
  compression: false
  debug: false
  verbose: false
  gzip: false

webmentions:
  debug: true
  pause_lookups: true

isso_host: comments.jacky.vagrant.test

pagination:
  debug: true

analytics:
  host: analytics.jacky.vagrant.test
  site_id: 1
