# vim: set nospell:
source: 'src'
destination: '_site'
layouts: 'src/_layouts'
plugins: 'plugins'

# Metadata about the site that we'd use very very often.
# {{{ Metadata
name: 'Jacky Alciné'
author: 'Jacky Alciné'
url: 'https://jacky.wtf'
description: |
  A young Black male from Brooklyn, New York in Oakland, California learning
  more about the world and now working to help make it way more secure for the
  people who live in it. So much to learn and yet so little time!
# }}}

# Time & encoding.
timezone: 'America/Los_Angeles'
encoding: 'utf-8'

permalink: "/weblog/:title/"
show_drafts: false
lsi: false
future: false
relative_permalinks: false
markdown: kramdown
highlighter: pygments

# Loading in the gems used by Jekyll. I really hate having to updating this
# list but it is what it is. 
gems:
  - jemoji
  - jekyll-gist
  - jekyll-sass
  - jekyll-haml
  - jekyll-timeago
  - jekyll-twitter-plugin
  - jekyll-auto-image
  - jekyll-paginate

# {{{ Markdown renderer options
kramdown:
  extensions:
    - footnotes
    - autolink
    - space_after_headers
    - highlight
    - fenced_code_blocks
    - disabled_indented_code_blocks
    - underline
    - with_toc_data
    - prettify
# }}}

defaults:
  -
    scope:
      path: ""
    values:
      components:
        header: true
        footer: true
