---
build_drafts: true
show_drafts: true
url: 'http://localhost:1993'
incremental: true

assets:
  compression: false
  gzip: false
  caching:
    enabled: true
  defaults:
    js:
      integrity: false
      prefetch: false
    css:
      integrity: false
      prefetch: false
    img:
      integrity: false
      prefetch: false

webmentions:
  debug: true
  pause_lookups: true

isso_host: comments.jacky.vagrant.test

pagination:
  debug: true

analytics:
  host: analytics.jacky.vagrant.test
  site_id: 1
