---
build_drafts: true
show_drafts: true
url: 'http://localhost:1993'
incremental: true

assets:
  debug: true
  autowrite: true
  strict: false
  digest: false
  integrity: false
  plugins:
    compression:
      css:
        enabled: false
      js:
        enabled: false

webmentions:
  pause_lookups: true
