# vim: nospell
# Generic values.
name: jalciné
url: http://jalcine.me
description: A little ol' collection of text and images.
timezone: America/New_York

# VCS data
git:
  branch: master
post:
  extension: markdown

# Blog specifics.
future: true
show_drafts: false
relative_permalinks: true
lsi: true
permalink: "/weblog/:title"
paginate: 5
paginate_path: "/weblog/page/:num"
category_dir: "weblog/categories"

# deployment
transfer:
  command: rsync
  settings: --delete --recursive --verbose
  source: _site/
  destination: jalcine.me:/var/www/jalcine.me/

# Markdown engine.
pygments: true
redcarpet:
  extensions:
    - footnotes
    - autolink
    - smart
    - tables
    - strikethrough
    - superscript

# Don't bother with theses.
exclude:
  - bin
  - "*.md"
  - "*file*"
  - "*config*"
  - sass
