---
build_drafts: true
show_drafts: true
incremental: true
verbose: true
url: 'http://localhost:1993'

assets:
  compression: false
  debug: false
  verbose: false
  gzip: false
  defaults:
    js:
      integrity: true
      prefetch: false
    css:
      integrity: true
      prefetch: false
    img:
      integrity: true
      prefetch: false

webmentions:
  debug: true
  pause_lookups: true

pagination:
  debug: true

isso_host: comments.jacky.vagrant.test

analytics:
  host: analytics.jacky.vagrant.test
  site_id: 1
