
source: 'src'
destination: '_site'
layouts: 'src/_layouts'
plugins: 'plugins'

# Metadata about the site that we'd use very very often.
# {{{ Metadata
name: 'Jacky Alciné'
author: 'Jacky Alciné'
url: 'https://jacky.wtf'
description: |
  The site of a young Black male living in New York City learning about the
  world and the people within it. The education he was brought up
  with was broken by default, and is currently attempting to learn what
  he should have known a decade ago.
# }}}

# Time & encoding.
timezone: 'America/New_York'
encoding: 'utf-8'

# {{{ Routing And Rendering
pagination_path: '/weblog/:num/'
permalink: '/weblog/:title/'
show_drafts: false
tag_dir: '/weblog/tag'
lsi: true
future: false
relative_permalinks: false
markdown: kramdown
highlighter: pygments
# }}}

# Loading in the gems used by Jekyll. I really hate having to updating this
# list but it is what it is. Might look into making 'jekyll-bundler' that has
# Jekyll load all of the gems under the 'jekyll' group in the Gemfile.
# {{{ Gems
gems:
  - jemoji
  - jekyll-gist
  - jekyll-sass
  - jekyll-haml
  - jekyll-timeago
  - jekyll-git_metadata
  - jekyll-twitter-plugin
  - jekyll-auto-image
  - octopress-quote-tag
# }}}

# {{{ Markdown renderer options
kramdown:
  extensions:
    - footnotes
    - autolink
    - space_after_headers
    - highlight
    - fenced_code_blocks
    - disabled_indented_code_blocks
    - underline
    - with_toc_data
    - prettify
# }}}

# {{{ Page Defaults
defaults:
  -
    scope:
      path: ""
      types: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      types: "posts"
    values:
      layout: "post"
# }}}
