# vim: nospell
name: "jalciné"
author: "Jacky Alciné"
url: "http://jalcine.me"
description: "A little collection of text and images."
timezone: "America/New_York"
source: src

# VCS data
git:
  branch: "master"
post:
  extension: "markdown"

# Blog specifics.
future: true
show_drafts: false 
relative_permalinks: false
lsi: false
permalink: "/weblog/:title"
paginate: 5
paginate_path: "/weblog/:num"

gems:
  - jekyll-compass
  - jekyll-haml

# Markdown engine.
pygments: true
redcarpet:
  extensions: 
    - footnotes
    - autolink
    - strikethrough
    - superscript
    - subscript
    - no_intra_emphasis
    - fenced_code_blocks
    - with_toc_data

# Don't bother with theses.
exclude:
  - 'bin'
  - "*.md"
  - "*file*"
  - "*config*"
  - 'sass'
  - '*tags*'

# Do it when I was born.
port: 1993
