# vim: nospell
name: "jalciné"
author: "Jacky Alciné"
url: "http://jalcine.me"
description: "A little ol' collection of text and images."
timezone: "America/New_York"

# VCS data
git:
  branch: "master"
post:
  extension: "markdown"

# Blog specifics.
future: true
show_drafts: true
relative_permalinks: false
lsi: false
permalink: "/weblog/:title"
paginate: 5
paginate_path: "/weblog/page/:num"

# Markdown engine.
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - 'footnotes'
    - 'autolink'
    - 'smart'
    - 'tables'
    - 'strikethrough'
    - 'superscript'

# Don't bother with theses.
exclude:
  - 'bin'
  - "*.md"
  - "*file*"
  - "*config*"
  - 'sass'

# Do it when I was born.
port: 1993

asset_pipeline:
  bundle: true
  compress: true
  output_path: 'assets'
  display_path: nil
  gzip: false
